Solution/01_AspNetMVC/Controllers/ContactsController.cs
using _01_AspNetMVC.Models.Dtos;
using _01_AspNetMVC.Services;
using _01_AspNetMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace _01_AspNetMVC.Controllers
{
	public class ContactsController : Controller
	{
		private readonly CommentsService _commentService;

		public ContactsController(CommentsService commentService)
		{
			_commentService = commentService;
		}

		public IActionResult Index()
		{
			//ContactFormViewModel model = new ContactFormViewModel();
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(ContactFormViewModel model)
		{
			if (ModelState.IsValid)
			{
				var result = await _commentService.CreateAsync(model);

				if (result.IsSuccessStatusCode)
					return RedirectToAction("Index", "Account");

				ModelState.AddModelError("", "Incorrect input");
			}

			return View(model);
		}
	}
}

Solution/01_AspNetMVC/Controllers/ProductsController.cs
using _01_AspNetMVC.Models.Dtos;
using _01_AspNetMVC.Services;
using _01_AspNetMVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace _01_AspNetMVC.Controllers
{
	public class ProductsController : Controller
	{
		private readonly ProductService _productService;

		public ProductsController(ProductService productService)
		{
			_productService = productService;
		}

		public async Task<IActionResult> Index()
		{
			CollectionViewModel model = new CollectionViewModel();
			model.Products = await _productService.GetAllAsync();

			return View(model);
		}

		public async Task<IActionResult> ProductDetails(int id)
		{
			var result = await _productService.GetByIdAsync(id);

            return View(result);
		}

	}
}

Solution/01_AspNetMVC/Views/Shared/_CollectionItemPartial.cshtml
@model Product

<div class="item">
    <div class="image-section">
        <img src="@Model.ImageUrl"
             alt="" />
        <div class="menu">
            <div class="icons">
                <button class="link">
                    <i class="fa-regular fa-code-compare"></i>
                </button>
                <button class="link">
                    <i class="fa-regular fa-heart"></i>
                </button>
                <button class="link">
                    <i class="fa-regular fa-bag-shopping"></i>
                </button>
            </div>
            <a class="btn-theme" asp-action="ProductDetails" asp-controller="Products" asp-route-id="@Model.Id">
                
                QUICK VIEW
            </a>
        </div>
    </div>
    <div class="body-section">
        <div class="category">@Model.Category!.CategoryName</div>
        <div class="name">@Model.Title</div>
        <partial name="_StarRatingPartial" model="@Model.StarRating"/>

        <div class="price">$@Model.Price</div>
    </div>
</div>

Solution/01_AspNetMVC/Views/Shared/_CollectionPartial.cshtml
@model IEnumerable<Product>

<section class="collection-grid">
    <div class="container">
        <div class="item-collection">

            @foreach(Product product in Model)
            {
                <partial name="_CollectionItemPartial" model="product"/>                        
            }
        </div>
    </div>
</section>

Solution/01_AspNetMVC/Views/Shared/_ContactFormPartial.cshtml
@model ContactFormViewModel

<section class="contact-form">
    <div class="container">
        <h1>Come in Contact with Us</h1>
        <form asp-controller="Contacts" asp-action="Index" method="post" class="container mt-4 " novalidate>
            
            <div asp-validation-summary="ModelOnly"></div>
            <div class="contact-form-name">
                <input asp-for="Name" placeholder="Your Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="contact-form-email">
                <input asp-for="Email" placeholder="Your Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="contact-form-comments">
                <textarea asp-for="CommentsText" id="comments" name="CommentsText" placeholder="Comments"></textarea>
                <span asp-validation-for="CommentsText" class="text-danger"></span>
            </div>

            <button class="btn-theme" type="submit">Post Comments</button>
        </form>
    </div>
</section>

Solution/01_AspNetMVC/Views/Shared/_FooterPartial.cshtml
<footer class="mt-5">
	<p class="fw-semibold text-center">&copy; @DateTime.Now.Year Fixxo. All Rights Reserved</p>
</footer>

Solution/01_AspNetMVC/Views/Shared/_HeaderPartial.cshtml
<header>
    <div class="container">
        <a id="logotype" href="/">Fixxo.</a>

        <div id="menu" class="">
            <nav class="menu-links links">
                <a class="link" href="/">Home</a>
                <a class="link" href="/contacts">Contacts</a>
            </nav>

            <nav class="menu-icons icons">
                <a class="link" href="/search"><i class="fa-regular fa-search"></i></a>
                <a class="link" href="/compare"><i class="fa-regular fa-code-compare"></i></a>
                <a class="link" href="/favorites"><i class="fa-regular fa-heart"></i></a>
                <a class="link" href="/cart"><i class="fa-regular fa-bag-shopping"></i></a>
                <a class="link ms-5" asp-action="Index" asp-controller="Account"><i class="fa-regular fa-user"></i></a>
            </nav>
        </div>

        <div id="toggle-icon" class="icons">
            <button class="link" data-option="toggle" data-target="#menu"><i class="fa-regular fa-bars"></i></button>
        </div>
    </div>
</header>

Solution/01_AspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://kit.fontawesome.com/41c8b474e2.css" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>@ViewData["Title"] - ASP.NET MVC</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <partial name="_HeaderPartial" />

    @RenderBody()

    <partial name="_FooterPartial" />

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Solution/01_AspNetMVC/Views/Shared/_ShowcasePartial.cshtml
<section class="showcase">
    <div class="container">
        <div class="content">
            <div class="title-2">GET UP TO 40% OFF</div>
            <div class="title-1">Don't Miss This Opportunity</div>
            <div class="title-3">Online shopping free home delivery over $100</div>
            <a class="btn-theme" href="/products">SHOP NOW</a>
        </div>
        <img src="~/images/showcase-img.png" alt="" />
    </div>
</section>

Solution/01_AspNetMVC/Views/Shared/_SpecialOfferPartial.cshtml
<div class="offer-grid container-fluid">
    <img id="office-style" src="~/images/office-style.png" alt="" />

    <div class="offer">
        <div class="red-border">
            <div class="content">
                <h1>50% Offer</h1>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis,
                    ipsam quo voluptatum facere iure fuga. Necessitatibus quasi
                    voluptatem delectus nam?
                </p>
                <button class="btn-white">FLASH SALE</button>
            </div>
        </div>
    </div>
    <img id="party-style" src="~/images/party-style.png" alt="" />
</div>

Solution/01_AspNetMVC/Views/Shared/_StarRatingPartial.cshtml
@model int

<div class="star-rating">

	@for (int i = 0; i < 5; i++)
	{
		string rating = "";

		if (Model <= i)
			rating = "fa-regular";
		else
			rating = "fa-solid";

		<i class="fa-sharp fa-star @rating"></i>
	}
</div>